// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace University.Models.Data
{
    [Table("students")]
    public partial class Student
    {
        [Key]
        [Column("stdID")]
        [StringLength(13)]
        public string StdId { get; set; }
        [Required]
        [Column("titleID")]
        [StringLength(2)]
        public string TitleId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("lastName")]
        [StringLength(50)]
        public string LastName { get; set; }
        [Column("birthay", TypeName = "date")]
        public DateTime Birthay { get; set; }
        [Required]
        [Column("phone")]
        [StringLength(10)]
        public string Phone { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [Column("address")]
        [StringLength(50)]
        public string Address { get; set; }
        [Required]
        [Column("districtID")]
        [StringLength(6)]
        public string DistrictId { get; set; }
        [Required]
        [Column("amphur")]
        [StringLength(4)]
        public string Amphur { get; set; }
        [Required]
        [Column("province")]
        [StringLength(2)]
        public string Province { get; set; }
        [Required]
        [Column("postcode")]
        [StringLength(5)]
        public string Postcode { get; set; }
        [Required]
        [Column("username")]
        [StringLength(25)]
        public string Username { get; set; }
        [Required]
        [Column("password")]
        [StringLength(300)]
        public string Password { get; set; }
        [Required]
        [Column("salt")]
        [StringLength(80)]
        public string Salt { get; set; }
    }
}